FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# winpty docker run -it -p 3000:3000 -v /app/node_modules -v "/$(PWD)":/app michielswaanen/front-end